# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a76a846eca9468e56a04d9bf3bb4c8feb59073aa54b4b11e72079a5d8d79069e03f126ba92880074ae29f33ed8fd4ae16fb86404b5b093ac5903255aa27ea8df

test:
  secret_key_base: ba820cbca9ffa75199051fc7585cb84c8d6335f71a1239a7d552e7789033fd8d7e1275de451e55ad23c45d418375c3cbf8e0cb2effdb055cff211d2e63664628

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
